### ISSUE TITLE
Please, release a version

### ISSUE THREAD

**Issue by eribertomota** [tanob/libofa#2]
Hi,

Initially, thanks for maintain alive this library. I am the libofa maintainer in Debian.

I am writing to ask you to release a new version. As help, there are patches that you can use here:

https://sources.debian.net/src/libofa/0.9.3-12/debian/patches/

I will send a email message for all my upstreams today, saying about the new Debian version.

Thanks a lot in advance.

Regards,

Eriberto

**Comment by tanob** [comment]
Can you clarify what you mean by releasing a new version? Do you mean merging some of those patches in this repo? Thanks!

**Comment by eribertomota** [comment]
2016-11-11 1:11 GMT-02:00 Adriano Bonat notifications@github.com:

> Can you clarify what you mean by releasing a new version? Do you mean
> merging some of those patches in this repo? Thanks!

Hi, thanks for your reply. To release a new version you must click over '0
releases > Draft a new release', after do some changes in source code. It
will generate a release, as shown here[1]. It is very important to all
Linux distributions to monitor changes in source code that generates new
releases and must be packaged by each maintainer in Debian, Fedora, Gentoo,
etc.

Yes, you can merge the patches and release a new version, if you want. The
current libofa release is 0.9.3. So, you should release a >= 0.9.4 version.

[1] https://github.com/eribertomota/axel/releases

Thanks a lot in advance.

Regards,

Eriberto

**Comment by tanob** [comment]
@eribertomota sorry, just noticed that I totally forgot about this issue. Please reopen it if you think this is still valid.
