### ISSUE TITLE
Outdated `config.guess` and `config.sub` file in source.

### ISSUE THREAD

**Issue by qyl27** [tanob/libofa#3]
I am trying to build libofa for riscv64 architecture.  
And got an outdated `config.guess` and `config.sub` files issue.  
Could you update it and release a new version?

**Comment by tanob** [comment]
Hi @qyl27 , do you mind opening a PR with the requested change?

**Comment by tanob** [comment]
Fixed by https://github.com/tanob/libofa/pull/4
